### ISSUE TITLE
NativeAOT Reflection-free mode exception.

### ISSUE THREAD

**Issue by josephmoresena** [JamesNK/Newtonsoft.Json.Schema#251]
I'm trying to validate a JObject against to JSchema into NativeAOT compiled assembly with reflection disabled.
The problem is are using Enum.GetValues(typeof(T)) into Newtonsoft.Json.Schema.Infrastructure.EnumHelpers.GetAllEnums<T>() function which is not work in this mode. [https://github.com/dotnet/runtimelab/blob/feature/NativeAOT/docs/using-nativeaot/reflection-free-mode.md](url)

The only one enum type which is passed as generic type to these functions is Newtonsoft.Json.Schema.JSchemaType.

**Comment by kvdrrrrr** [comment]
I don't think this is an issue relevant to this project. As a temporary solution, I suggest weaving the assemblies before passing them to ILCompiler. Find all references of Enum.GetValues, precompute value table for each referenced enum type and use that table instead of Enum.GetValues. Unfortunately, using Fody is out of question since it does not support weaving 3rd party assemblies. Good luck!

**Comment by kvdrrrrr** [comment]
[i did it with dnlib](https://gist.github.com/kvdrrrrr/5137913a2fe6ebd252a84c424a904939)
You still need to rewire compiler responses yourself, or just reference fixed assemblies directly
