### ISSUE TITLE
Properties next to a `$ref` are not ignored and cause an invalid schema to be generated

### ISSUE THREAD

**Issue by sfwester** [JamesNK/Newtonsoft.Json.Schema#285]
From the [draft 6 specification section 8 "Schema references with $ref"](https://datatracker.ietf.org/doc/html/draft-wright-json-schema-01#section-8)
> All other properties in a "$ref" object MUST be ignored.

The following program (using `Newtonsoft.Json.Schema 3.0.14`)
```cs
using System;
using Newtonsoft.Json.Schema;

namespace Tinker
{
    class Program
    {
        static void Main(string[] args)
        {
            string refSchema = @"{
                ""type"": ""string""
            }";

            JSchemaPreloadedResolver resolver = new JSchemaPreloadedResolver();
            resolver.Add(new Uri("refSchema", UriKind.RelativeOrAbsolute), refSchema);

            JSchema schemaWithoutTitle = JSchema.Parse(@"{
                ""$ref"": ""refSchema""
            }", resolver);

            JSchema schemaWithTitle = JSchema.Parse(@"{
                ""title"": ""A Title"",
                ""$ref"": ""refSchema""
            }", resolver);

            Console.WriteLine(schemaWithoutTitle);
            Console.WriteLine("---");
            Console.WriteLine(schemaWithTitle);

            JSchema.Parse(schemaWithTitle.ToString());
        }
    }
}
```
produces the following output
```txt
{
  "type": "string"
}
---
{
  "title": "A Title",
  "$ref": "#/$ref"
}
```
and then throws
```txt
Unhandled exception. Newtonsoft.Json.Schema.JSchemaReaderException: Could not resolve schema reference '#/$ref'. Path '', line 1, position 1.
```

I would expect it to output
```txt
{
  "type": "string"
}
---
{
  "type": "string"
}
```
and not throw since we now have a valid schema.

**Comment by elgonzo** [comment]
I don't know if the produced `"$ref": "#/$ref"` is in accordance with the current Json schema version.

However, the expected behavior is _**NOT**_ a bug. The behavior as specified in draft 6 is not part of the Json schema spec since draft 2019-09. From [section 8.2.4.1](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02#section-8.2.4.1):
>  The "$ref" keyword is an applicator that is used to reference a statically identified schema.  Its results are the results of the referenced schema.  [[CREF9: Note that this definition of how the results are determined means that **_other keywords can appear alongside of "$ref" in the same schema object_**.  ]]

and further clarified in [appendix B.2](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02#appendix-B.2):
> [...] Since "$ref" is now treated like any other keyword, with other keywords allowed in the same schema objects, [...]

<BR>

That said, Newtonsoft.Json.Schema actually supports Json schema draft 6. You just have to tell it to use draft 6.

Unfortunately, i do not know how to do that in code through the library's API. There might be a way, but i am unaware of any such. The only way i know of is by specifiying the Json schema version through the $schema keyword in the schema itself. Basically, if you add the $schema keyword with the appropriate schema draft 6 uri like:
```C#
JSchema schemaWithTitle = JSchema.Parse(@"{
    ""$schema"": ""http://json-schema.org/draft-06/schema#/schema-draft-v6.json"",
    ""title"": ""A Title"",
    ""$ref"": ""refSchema""
    }", resolver);
```
you will get the desired result.

Dotnetfiddle: https://dotnetfiddle.net/jnBJAB

**Comment by sfwester** [comment]
Thanks for the tip getting my example behaving the way I expected.

I was under the impression this library only supported draft 6 and below based on the note [here](https://www.newtonsoft.com/jsonschema/help/html/Introduction.htm)

> Supports 100% of JSON Schema Draft 6 and has backwards compatibility with older versions

I see on the main page now that 2019-09 is supported, that is great news for us.

I'll create a new issue to see what should be done about the `"$ref": "#/$ref"` issue.
