### ISSUE TITLE
No Configuration for Generating External References

### ISSUE THREAD

**Issue by dagrooms52** [JamesNK/Newtonsoft.Json.Schema#58]
I just started using the JSON Schema generator to generate schemas for a class library project of mine. These classes interact to create an object tree. Each class gets a schema created for it, and I would expect that there would be some way to point these files at each other to reuse schemas and avoid code repetition, but there doesn't seem to be a way to do so. Class definitions are just inlined in the schema instead, or placed in the human-readable references section. Some configuration as simple as `GenerateExternalReferences` option and a `BaseReferenceUri` to append each schema's ID to would be great.

**Comment by JamesNK** [comment]
Hi

Would you want *every* separate type be an external reference? Do you image that every type that would have been placed in `definitions` would instead be a reference to an external schema?

I think this might be complicated because JSchemaGenerator focuses on generating the types. Actually writing them is done completely separately. There would need to be configuration that would span both actions to achieve what I think you want.

**Comment by dagrooms52** [comment]
It does seem to me now that you would have to expect the user to generate every schema, or risk producing broken references in the final result, especially if they use classes in their schema that they did not define and will not be generating JSchema for. Do you think it would be possible to configure the generator to not inline classes in a given assembly, or a namespace, but instead place an external reference for these types? This way, the user takes responsibility for generating the external references and still has a way to say which references they will define, so that types which aren't in the assembly or namespace they configure the generator with will still be inlined.
